name: ComfyWhitelist
api-version: 1.13
authors:
  - cocahonka
  - vmlakk
main: com.cocahonka.comfywhitelist.ComfyWhitelist
version: @version@
softdepend: ["kotlin-stdlib"]
commands:
  comfywhitelist:
    description: ComfyWhitelist management.
    aliases: [ comfywl ]
    permission: comfywhitelist.comfywhitelist
permissions:
  comfywhitelist.*:
    description: Give access to all ComfyWhitelist commands.
    default: op
    children:
      comfywhitelist.add: true
      comfywhitelist.remove: true
      comfywhitelist.list: true
      comfywhitelist.check: true
  comfywhitelist.comfywhitelist:
    description: Give access to main ComfyWhitelist command.
    default: op
  comfywhitelist.add:
    description: Give access to add player name to ComfyWhitelist.
    default: op
  comfywhitelist.remove:
    description: Give access to remove player name from ComfyWhitelist.
    default: op
  comfywhitelist.list:
    description: Give access to display all player names in ComfyWhitelist.
    default: op
  comfywhitelist.check:
    description: Give access to check player whitelist status.
    default: op
